name: Deploy Website to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Pre Deployment Validation
      - name: Validate Project Files
        run: |
          echo "Checking required files..."
          test -f index.html
          test -f style.css
          test -f about.html
          test -f contact.html
          echo "All required files found."

      # Deploy to EC2
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22

          script: |

            echo " Connected to EC2"

            cd /tmp

            if [ -d automated-cicd-pipeline ]; then
                cd automated-cicd-pipeline
                git pull origin main
            else
                git clone https://github.com/vedantk233/automated-cicd-pipeline.git
                cd automated-cicd-pipeline
            fi

            echo " Preparing deployment..."

            sudo rm -rf /tmp/new-site
            sudo mkdir -p /tmp/new-site

            # Required files
            sudo cp index.html /tmp/new-site/
            sudo cp about.html /tmp/new-site/
            sudo cp contact.html /tmp/new-site/
            sudo cp style.css /tmp/new-site/

            # Copy JS only if available
            if [ -f script.js ]; then
              sudo cp script.js /tmp/new-site/
            fi

            # Copy images folder only if available
            if [ -d images ]; then
              sudo cp -r images /tmp/new-site/
            fi

            echo " Replacing website..."

            sudo rm -rf /var/www/html/*
            sudo cp -r /tmp/new-site/* /var/www/html/

            echo " Setting permissions..."

            sudo find /var/www/html -type d -exec chmod 755 {} \;
            sudo find /var/www/html -type f -exec chmod 644 {} \;

            echo " Restarting Apache..."

            sudo systemctl restart apache2

            echo " Verifying Website..."

            curl -I http://localhost

            echo " Deployment Completed Successfully!"