name: Deploy Website to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "Connected to EC2"

            cd /tmp

            if [ -d "automated-cicd-pipeline" ]; then
              cd automated-cicd-pipeline
              git pull origin main
            else
              git clone https://github.com/vedantk233/automated-cicd-pipeline.git
              cd automated-cicd-pipeline
            fi

            sudo rm -rf /var/www/html/*
            sudo cp -r . /var/www/html/
            sudo chmod -R 755 /var/www/html/
            sudo systemctl restart apache2

            echo "Deployment Successful!"